### ISSUE TITLE
PhantomJS should be listed as a dependency for running tests.

### ISSUE THREAD

**Issue by samrat** [nilenso/wscljs#4]
Running `lein test` without PhantomJS installed throws an error. The README should probably mention that PhantomJS should be installed before running tests.

**Comment by kirang89** [comment]
This had completely slipped my mind. I've fixed this in [#c07c7d](https://github.com/nilenso/wscljs/commit/c07c7d74294154f1e3b3c3778a4a62e944cce1d0). 

Thanks for pointing this out :)

**Comment by palfrey** [comment]
Turns out that PhantomJS 1.9.7 (which I had installed) isn't enough. 2.1.1 which I replaced it with was.

**Comment by kirang89** [comment]
@palfrey I've updated the README to add a note about using Phantom 2.x. Thanks!
